/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_calculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void dummyTest() {
        assertNull("null is null", null);
    }
}
